/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.junandaip.calctest;

public class App {
    double hasil = 0;

    @Override
    public String toString() {
        return "Hasil :" + this.hasil;
    }
}
