/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.junandaip.calctest;

public class Calculator {
    private double result = 1;

    public String cancel() {
        return String.valueOf(this.result = 0);
    }

    public String add(double input) {
        double calculate = this.result + input;
        return  String.valueOf(calculate);
    }

    public String subtract(double input) {
        double calculate = this.result - input;
        return  String.valueOf(calculate);
    }

    @Override
    public String toString() {
        return this.result+"";
    }
}
