/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.junandaip.calctest;

public class Calculator {
    private double result = 1;

    public double cancel() {
        return this.result = 0;
    }

    public double add(double number) {
        return this.result += number;
    }

    public double subtract(double number) {
        return this.result -= number;
    }

    @Override
    public String toString() {
        return String.format("%.1f", this.result);
    }
}
