/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.junandaip.calctest;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testCalcCancel() {
        App classUnderTest = new App();
        int result = 10;
        int canc_result = result*0;
        assertEquals(canc_result, );
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
