/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.junandaip.calctest;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testToString() {
        App classUnderTest = new App();
        assertEquals("0",classUnderTest.toString());
    }
}
